version: "3.8"

services:
  docker-prac-redis:
    container_name: myapp-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: 2eungwoo/docker-prac-redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "6379:6379"

  docker-prac-mysql:
    container_name: myapp_mysql
    build:
      dockerfile: Dockerfile
      context: ./mysql
    image: 2eungwoo/docker-prac-mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - ./mysql/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  docker-prac-app:
    container_name: myapp-application
    build:
      dockerfile: Dockerfile
      context: .
    depends_on: # redis, mysql container run -> app container run
      - docker-prac-redis
      - docker-prac-mysql
    image: 2eungwoo/docker-prac-application
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    restart: always

# ports : {컨테이너_외부}:{컨테이너_내부}

